name: DevSecOps Pipeline (Cloud)

on: [push, pull_request]

jobs:

  unit-test:
    name: Tests unitaires & couverture
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci --ignore-scripts
      - run: npm test
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: coverage-report
          path: coverage/

  sonar-check:
    name: Analyse SonarQube Cloud
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: coverage-report
          path: coverage/
      - uses: SonarSource/sonarqube-scan-action@2f77a1ec69fb1d595b06f35ab27e97605bdef703 # v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io

  dependency-scan:
    name: Scan dependances (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: aquasecurity/trivy-action@cf5c088a69634cd13ccddc735d7926162c31f9a6 # master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          format: 'table'

  build-image:
    name: Build image Docker
    needs: [sonar-check, dependency-scan]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Build
        run: docker build -t webapp:${{ github.sha }} .
      - name: Sauvegarde image
        run: docker save webapp:${{ github.sha }} -o webapp.tar
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: docker-image
          path: webapp.tar

  container-scan:
    name: Scan image Docker (Trivy)
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: docker-image
      - name: Chargement image
        run: docker load -i webapp.tar
      - uses: aquasecurity/trivy-action@cf5c088a69634cd13ccddc735d7926162c31f9a6 # master
        with:
          scan-type: 'image'
          image-ref: 'webapp:${{ github.sha }}'
          severity: 'CRITICAL'
          exit-code: '1'
          format: 'table'
